[package]
name = "binius-frontend"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
binius-compute = { path = "../compute" }
binius-core = { path = "../core" }
binius-field = { path = "../field" }
binius-utils = { path = "../utils" }
cranelift-entity = { workspace = true }
itertools.workspace = true
petgraph.workspace = true
serde.workspace = true
serde_json.workspace = true
smallvec.workspace = true
thiserror.workspace = true
rustc-hash.workspace = true

[dev-dependencies]
rand = { workspace = true, features = ["thread_rng"] }
proptest = { workspace = true }
insta = { workspace = true }
trybuild = { workspace = true }
